export const lithoProducts = [
  {
    name: "Литография sleek",
    volume: "250 мл",
    height: "133.2 мм",
    diameter: "53 мм",
    wall: "0.10 мм",
    material: "Пищевой алюминий",
    coating: "BPA-NI внутреннее покрытие",
    bestFor: "Энергетики, тоники, функциональные напитки",
    colors: "До 8 цветов печати",
    icon: "Zap",
    popular: false,
  },
  {
    name: "Литография sleek",
    volume: "330 мл",
    height: "115.2 мм",
    diameter: "66.3 мм",
    wall: "0.170 мм",
    material: "Алюминиевый сплав",
    coating: "Внутренний лак на водной основе",
    bestFor: "Пиво, сидр, газированные напитки",
    colors: "До 8 цветов печати",
    icon: "Star",
    popular: true,
  },
  {
    name: "Литография",
    volume: "449 мл",
    height: "168.0 мм",
    diameter: "63.5 мм",
    wall: "0.170 мм",
    material: "Алюминиевый сплав",
    coating: "Внутренний лак на водной основе",
    bestFor: "Пиво, коктейли, лимонады",
    colors: "До 8 цветов печати",
    icon: "Maximize",
    popular: false,
  },
];

export const specRows = [
  { key: "height", label: "Высота" },
  { key: "diameter", label: "Диаметр" },
  { key: "wall", label: "Стенка" },
  { key: "material", label: "Материал" },
  { key: "coating", label: "Покрытие" },
  { key: "bestFor", label: "Применение" },
  { key: "colors", label: "Цвета печати" },
] as const;

export const galleryItems = [
  {
    id: 1,
    title: "Крафтовое пиво",
    subtitle: "Серия ограниченного выпуска",
    accent: "#c9a84c",
    rotate: -3,
    size: "large",
    image: "https://cdn.poehali.dev/projects/c29c3c15-8a3c-4d61-959d-3782d069fcee/bucket/e9cea27a-ce04-4b49-a24c-12f3239d2c3d.png",
  },
  {
    id: 2,
    title: "Энергетик Pro",
    subtitle: "Городская коллекция",
    accent: "#e8c97a",
    rotate: 1.5,
    size: "small",
    image: "https://cdn.poehali.dev/projects/c29c3c15-8a3c-4d61-959d-3782d069fcee/bucket/a8f9c300-fa1f-4661-9d12-b9612289e2bc.png",
  },
  {
    id: 3,
    title: "Лимонад Premium",
    subtitle: "Летняя серия",
    accent: "#c9a84c",
    rotate: -1,
    size: "small",
    image: "https://cdn.poehali.dev/projects/c29c3c15-8a3c-4d61-959d-3782d069fcee/bucket/6bb143ef-f508-4d58-8d95-0a2e3e2e1d64.png",
  },
  {
    id: 4,
    title: "Коктейль Edition",
    subtitle: "Авторский дизайн",
    accent: "#8a6e2f",
    rotate: 2.5,
    size: "large",
  },
  {
    id: 5,
    title: "Сидр Artisan",
    subtitle: "Фермерская коллекция",
    accent: "#e8c97a",
    rotate: -2,
    size: "small",
  },
  {
    id: 6,
    title: "Тоник Royal",
    subtitle: "Классическая серия",
    accent: "#c9a84c",
    rotate: 1,
    size: "small",
    image: "https://cdn.poehali.dev/projects/c29c3c15-8a3c-4d61-959d-3782d069fcee/bucket/7ddd6ce1-973f-41c4-b99c-c0d0a20b437a.png",
  },
];